// Generated by gen_abi.zig - DO NOT EDIT (Manually synced by assistant)

pub const SYS_CAP_CREATE: usize = 1;
pub const SYS_CAP_DELETE: usize = 2;
pub const SYS_CAP_REVOKE: usize = 3;
pub const SYS_CAP_TRANSFER: usize = 4;
pub const SYS_CAP_MINT: usize = 5;
pub const SYS_CAP_VERIFY: usize = 6;

pub const SYS_IPC_SEND: usize = 10;
pub const SYS_IPC_RECV: usize = 11;
pub const SYS_IPC_CALL: usize = 12;
pub const SYS_IPC_REPLY: usize = 13;

pub const SYS_MAP_MEMORY: usize = 12; // Added per user request
pub const SYS_RETYPE: usize = 20;
pub const SYS_MAP_FRAME: usize = 21;
pub const SYS_UNMAP_FRAME: usize = 22;

pub const SYS_THREAD_CREATE: usize = 30;
pub const SYS_THREAD_RESUME: usize = 31;
pub const SYS_THREAD_SUSPEND: usize = 32;
pub const SYS_THREAD_SET_PRIORITY: usize = 33;

pub const SYS_ENDPOINT_CREATE: usize = 40;
pub const SYS_ENDPOINT_DELETE: usize = 41;
pub const SYS_NAMESPACE_REGISTER: usize = 42;

pub const SYS_DEBUG_PUTCHAR: usize = 99;
pub const SYS_DEBUG_DUMP_CAPS: usize = 98;

pub const RIGHT_READ: usize = 1;
pub const RIGHT_WRITE: usize = 2;
pub const RIGHT_GRANT: usize = 4;
pub const RIGHT_MAP: usize = 8;
