#!/usr/bin/env bash
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

status=0

print_section() {
  printf '\n== %s ==\n' "$1"
}

print_missing() {
  printf '%s: missing\n' "$1"
}

json_summary() {
  local label="$1"
  local path="$2"
  local mode="$3"

  print_section "$label"

  if [[ ! -f "$path" ]]; then
    print_missing "$path"
    return 0
  fi

  if ! python3 - "$path" "$mode" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
mode = sys.argv[2]

try:
    data = json.loads(path.read_text())
except json.JSONDecodeError as exc:
    print(f"{path}: malformed JSON: {exc}")
    raise SystemExit(2)


def get(mapping, key, default="unknown"):
    value = mapping.get(key, default)
    return default if value in (None, "") else value


def list_line(values):
    if not values:
        return "none"
    return ", ".join(str(value) for value in values)


if mode == "latest_verify":
    summary = data.get("summary", {})
    failed = data.get("failed_checks", [])
    print(f"status: {get(data, 'status')}")
    print(f"summary_code: {get(data, 'summary_code')}")
    print(f"total_checks: {summary.get('total_checks', 'unknown')}")
    print(f"failed_check_count: {summary.get('failed_check_count', 'unknown')}")
    if failed:
        print("failed_checks:")
        for check in failed:
            name = get(check, "name")
            code = get(check, "code")
            detail = get(check, "detail")
            print(f"- {name}: {code}: {detail}")
    else:
        print("failed_checks: none")
elif mode == "qemu_smoke":
    print(f"outcome: {get(data, 'outcome')}")
    print(f"blocker_category: {get(data, 'blocker_category', 'none')}")
    print(f"expected_marker: {get(data, 'expected_marker')}")
    print(f"observed_markers: {list_line(data.get('observed_markers', []))}")
    print(f"qemu_exit_code: {get(data, 'qemu_exit_code')}")
    print(f"timed_out: {get(data, 'timed_out')}")
    print(f"serial_log_bytes: {get(data, 'serial_log_bytes')}")
    print(f"stderr_log_bytes: {get(data, 'stderr_log_bytes')}")
elif mode == "boot_blocker":
    print(f"outcome: {get(data, 'outcome')}")
    print(f"blocker_category: {get(data, 'blocker_category', 'none')}")
    missing = data.get("missing_components", [])
    if missing:
        print("missing_components:")
        for item in missing:
            print(f"- {item}")
    else:
        print("missing_components: none")
    print(f"next_required_fix: {get(data, 'next_required_fix')}")
else:
    print(f"{path}: unknown summary mode {mode}")
    raise SystemExit(2)
PY
  then
    status=1
  fi
}

print_file_or_missing() {
  local label="$1"
  local path="$2"

  print_section "$label"

  if [[ -f "$path" ]]; then
    cat "$path"
  else
    print_missing "$path"
  fi
}

tail_file_or_missing() {
  local label="$1"
  local path="$2"

  print_section "$label"

  if [[ -f "$path" ]]; then
    tail -n 80 "$path"
  else
    print_missing "$path"
  fi
}

print_section "CI Evidence Summary"
printf 'Generated by: scripts/ci_evidence_summary.sh\n'

json_summary "Latest Verification Status" "artifacts/latest_verify.json" "latest_verify"
json_summary "QEMU Smoke Metadata" "artifacts/runtime/qemu_smoke.metadata.json" "qemu_smoke"
print_file_or_missing "QEMU Smoke Summary" "artifacts/runtime/qemu_smoke.summary.txt"
tail_file_or_missing "Last 80 QEMU Serial Log Lines" "artifacts/runtime/qemu_smoke.log"
tail_file_or_missing "Last 80 QEMU Stderr Log Lines" "artifacts/runtime/qemu_smoke.stderr.log"
json_summary "Boot Blocker Report" "artifacts/runtime/boot_blocker_report.json" "boot_blocker"

exit "$status"
