const std = @import("std");

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: {s} <input_zig_file> <output_rs_file>\n", .{args[0]});
        std.process.exit(1);
    }

    const input_path = args[1];
    const output_path = args[2];

    const file = try std.fs.cwd().openFile(input_path, .{});
    defer file.close();

    const output_file = try std.fs.cwd().createFile(output_path, .{});
    defer output_file.close();

    var writer = output_file.writer();
    try writer.writeAll("// Generated by gen_abi.zig - DO NOT EDIT\n\n");

    var buf_reader = std.io.bufferedReader(file.reader());
    var in_stream = buf_reader.reader();
    var buf: [1024]u8 = undefined;

    while (try in_stream.readUntilDelimiterOrEof(&buf, '\n')) |line| {
        // Simple parser for 'pub const SYS_...' or 'pub const RIGHT_...'
        if (std.mem.indexOf(u8, line, "pub const ") != null) {
            var it = std.mem.tokenizeAny(u8, line, " =:;");
            _ = it.next(); // "pub"
            _ = it.next(); // "const"
            const name = it.next() orelse continue;
            
            // Skip types like u32
            var val_token = it.next() orelse continue;
            if (std.mem.eql(u8, val_token, "u32") or std.mem.eql(u8, val_token, "usize")) {
                val_token = it.next() orelse continue;
            }

            try writer.print("pub const {s}: usize = {s};\n", .{name, val_token});
        }
    }
}
